godwokenrises/godwoken-doc

docs/intro.md
Please review this change for the word of caution. Thanks.
=> To add word of caution

package-lock.json, package.json, versioned_docs/version-1.2-rc1(WIP)/connectionInfo.md, versioned_docs/version-1.2-rc1(WIP)/faq.md, versioned_docs/version-1.2-rc1(WIP)/getStart.md, versioned_docs/version-1.2-rc1(WIP)/overview.md, versioned_docs/version-1.2-rc1(WIP)/v0difv1.md, versioned_sidebars/version-1.2-rc1(WIP)-sidebars.json, yarn.lock
2 docs modified:
- fast withdrawal references modified
- connection info mainnet token bridge domain modified
=> modifications

versioned_docs/version-1.3-rc1(WIP)/pCKB.md, versioned_docs/version-1.3-rc1(WIP)/v0difv1.md
Changed or added some info to the docs. 
If any of my words/sentences are wrong, please let me know.
Changes in the PR:
- Explained decimals difference between CKB and pCKB in `pCKB.md`
- Modified min_gasPrice value in `v0difv1.md` from 9E13 to 4E13
=> Update pCKB related docs

versioned_docs/version-1.3-rc1(WIP)/getStart.md
line 13: adds Like -  its -> it's - changes costs -> fees - adds Ethereum faces. 
line 15: removes And - Godwoekn -> Godwoken 
line 17: adds currently - , allowing -> . Allowing - comma after finality
line 19: to -> on how - in the Godwoken -> with Godwoken 
line 30: know ->  find 
line 31: in -> to - at -> here
=> Fixes syntax

docusaurus.config.js
changes:
```
themeConfig: {
colorMode: {
...
disableSwitch: false,
...
navbar: {
...
style: "dark",
```
=> fix - dark mode enabled.

versioned_docs/version-1.3-rc1(WIP)/covalent.md, versioned_sidebars/version-1.3-rc1(WIP)-sidebars.json
=> Add Covalent documentation page

versioned_docs/version-1.4(WIP)/oracles.md
Remove information about DIA due to mainnet oracle being "strictly for testing purposes".
=> remove information about DIA

docs/releaseNote1.5.md, docs/web3Change1.6.md, versioned_docs/version-1.4(WIP)/web3changelog/web3Change1.5.md
- updated gw-web3 v1.5 changelog
- created gw v1.5 changelog
- created gw-web3 v1.6 changelog
=> release notes update

versioned_docs/version-1.5(WIP)/connectionInfo.md, versioned_docs/version-1.5(WIP)/gwScripts.md, versioned_docs/version-1.5(WIP)/gwchangelog/releaseNote1.1.md, versioned_docs/version-1.5(WIP)/gwchangelog/releaseNote1.5.md, versioned_docs/version-1.5(WIP)/quickstart.md, versioned_sidebars/version-1.5(WIP)-sidebars.json
include:
- modified config file
- fixed typos
=> content mods

versioned_docs/version-1.5(WIP)/connectionInfo.md, versioned_docs/version-1.5(WIP)/frameworks.md, versioned_docs/version-1.5(WIP)/overview.md, versioned_sidebars/version-1.5(WIP)-sidebars.json
- Modification of the v1.5 sidebar config file
- Minor adjustments to layout
=> Layout changes

docs/claimFaucet.md, sidebars.js
Added a tutorial about how to claim faucet on Godwoken testnet_v1.
Make sure to fulfill the checklist before merging.
=> Docs: claim assets on testnet v1

.github/workflows/deploy.yml, .github/workflows/test-deploy.yml
- https://docusaurus.io/docs/deployment#triggering-deployment-with-github-actions
=> chore: trigger deployment automatically on main branch

dependabot.yml
Trying to make the dependabot ignore some of our dependencies.
The refference docs: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
=> chore: add dependabot configure file

docs/gaslessApi.md, docs/gaslessFeature.md, sidebars.js
- https://github.com/godwokenrises/godwoken/discussions/860
=> First draft for initial observation of gas-less feature

docs/gaslessFeature.md
Fix the description on configuring paymaster. And add more details.
Render version: https://github.com/magicalne/godwoken-doc/blob/gasless_update/docs/gaslessFeature.md#how-to-configure-a-paymaster-contract
=> chore: elaborate on gasless feature

docs/gaslessFeature.md
Rendered version: https://github.com/magicalne/godwoken-doc/blob/gasless/docs/gaslessFeature.md
=> chore: fix gasless code error and add more description

docs/debugRPC.md
=> Fix the style of `Steps` in debug-replay-rpc.md

docs/claimFaucet.md, docs/connectionInfo.md
https://faucet-testnet.godwoken.io
=> Update the link of `Testnet pCKB Faucet`

docs/otherTools.md
4. [Multicall3](https://github.com/mds1/multicall): Multicall aggregates results from multiple contract constant function calls.
- Godwoken mainnet: https://gwscan.com/account/0xcA11bde05977b3631167028862bE2a173976CA11?tab=contract
- Godwoken testnet: https://v1.testnet.gwscan.com/account/0xcA11bde05977b3631167028862bE2a173976CA11?tab=contract
- Verified in Sourcify https://sourcify.dev/#/lookup/0xcA11bde05977b3631167028862bE2a173976CA11
=> Update the info of Multicall3

docs/evm_training/evmTask2.md, src/css/custom.css
- change the document structure 
- add the missing file 
- update some error path
=> Update evmtraining2 20230511

docs/thirdweb.md
hey! I've added utm sources to our links for tracking
=> chore: add utm sources to links

docs/connectionInfo.md, docs/deployLocalNetwork.md, docs/evm_training/evmTask4.md, docs/frameworks.md, docs/getStart.md, docs/godwokenkicker.md, docs/gwScripts.md, docs/overview.md, docs/reference.md, docs/thirdweb.md
Some fixes on the doc I made when I went though the doc.
the deleting of extra space is made by my editor :)
=> Some trivial fixes on writing
